// This code was generated by a tool, changes to this will be lost if the code is regenerated. #region ranges X:Method will be preseved
using System;
using System.Abstract;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace CORE.Site
{
    public class ${Name}Controller : ApiController
    {
        readonly I${Name}Repository _${name}Repository;
        readonly I${Name}ServiceRepository _${name}ServiceRepository;
        
        public ${Name}Controller() : this(ServiceLocator.Resolve<I${Name}Repository>(),
            ServiceLocator.Resolve<I${Name}ServiceRepository>()) { }
        public ${Name}Controller(I${Name}Repository ${name}Repository,
            I${Name}ServiceRepository ${name}ServiceRepository)
        {
            _${name}Repository = ${name}Repository;
            _${name}ServiceRepository = ${name}ServiceRepository;
        }

        // GET api/<controller>
        public IEnumerable<${Name}Model> Get(string sort = null)
        {
            return _${name}Repository.GetAll();
        }

        // GET api/<controller>/5
        public ${Name}Model Get(Guid id)
        {
            return _${name}Repository.GetById(id);
        }

        // POST api/<controller>
        public void Post([FromBody]string value)
        {
        }

        // PUT api/<controller>/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/<controller>/5
        public bool Delete(Guid id)
        {
            return _${name}ServiceRepository.DeleteById(id);
        }
    }
};