// This code was generated by a tool, changes to this will be lost if the code is regenerated. #region ranges X:Method will be preseved
using System;
using System.Linq;
using System.Collections.Generic;
using Dapper;

namespace CORE.Site
{
    public interface I${Name}Repository
    {
        IEnumerable<${Name}Model> GetAll();
        ${Name}Model GetById(Guid id);
    }

    public class ${Name}Repository : I${Name}Repository
    {
        readonly IStorageService _storageService;

        public ${Name}Repository(IStorageService storageService)
        {
            _storageService = storageService;
        }

        public IEnumerable<${Name}Model> GetAll()
        {
            using (var ctx = _storageService.GetConnection())
                foreach (var i in ctx.Query<${Name}Model>('${0}', new { }))
                    yield return i;
        }

        public ${Name}Model GetById(Guid id)
        {
            using (var ctx = _storageService.GetConnection())
                return ctx.Query<${Name}Model>('${1}', new { ${Name}Id = id })
                    .SingleOrDefault();
        }
    }
}