// This code was generated by a tool, changes to this will be lost if the code is regenerated. #region ranges X:Method will be preseved
using System;
using System.Linq;
using System.Collections.Generic;
using Dapper;

namespace CORE.Site
{
    public interface I${Name}ServiceRepository
    {
        bool DeleteById(Guid id);
    }

    public class ${Name}ServiceRepository : I${Name}ServiceRepository
    {
        readonly IStorageService _storageService;

        public ${Name}ServiceRepository(IStorageService storageService)
        {
            _storageService = storageService;
        }
        
        public bool DeleteById(Guid id)
        {
            using (var ctx = _storageService.GetConnection())
                return (ctx.Execute('${0}', new { ${Name}Id = id }) > 0);
        }
    }
}